nc_interface_index:
    pattern:  /do/
    defaults: { _controller: BrainstrapCoreNCBundle:Default:index }

nc_settings_index:
    pattern:  /do/settings/
    defaults: { _controller: BrainstrapCoreNCBundle:Settings:index }