nc_interface_index:
    pattern:  /do/
    defaults: { _controller: BrainstrapCoreNCBundle:Default:index }

nc_settings_index:
    pattern:  /do/settings/
    defaults: { _controller: BrainstrapCoreNCBundle:Settings:index }

nc_reports_index:
    pattern:  /do/reports/
    defaults: { _controller: BrainstrapCoreNCBundle:Reports:index }

BrainstrapCoreNCBundle_client:
    resource: "@BrainstrapCoreNCBundle/Resources/config/routing/client_client.yml"
    prefix:   /client

BrainstrapCoreNCBundle_cart:
    resource: "@BrainstrapCoreNCBundle/Resources/config/routing/cart_cart.yml"
    prefix:   /cart

BrainstrapCoreNCBundle_cart_type:
    resource: "@BrainstrapCoreNCBundle/Resources/config/routing/cart_carttype.yml"
    prefix:   /cart/type

BrainstrapCoreNCBundle_session_personalsession:
    resource: "@BrainstrapCoreNCBundle/Resources/config/routing/session_personalsession.yml"
    prefix:   /session/personalsession

BrainstrapCoreNCBundle_session_groupsession:
    resource: "@BrainstrapCoreNCBundle/Resources/config/routing/session_groupsession.yml"
    prefix:   /session/groupsession

info_total:
    pattern:  /total/info/all
    defaults: { _controller: BrainstrapCoreNCBundle:Info/Info:totalAll }

info_money_total:
    pattern:  /total/info/money
    defaults: { _controller: BrainstrapCoreNCBundle:Info/Info:totalMoney }

info_client_total:
    pattern:  /total/info/client
    defaults: { _controller: BrainstrapCoreNCBundle:Info/Info:totalClient}

info_session_total:
    pattern:  /total/info/session
    defaults: { _controller: BrainstrapCoreNCBundle:Info/Info:totalSession}