parameters:
#    brainstrap_core_nc.example.class: Brainstrap\Core\NCBundle\Example

services:
#    brainstrap_core_nc.example:
#        class: %brainstrap_core_nc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
