<?php
namespace Brainstrap\Core\NCBundle\Repository\Cart;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
	public function findCartByCode($code)
	{
		$query = $this->createQueryBuilder('cart')
			->where('cart.code = :code')
			->setParameter('code', $code)
			->getQuery();

		return $query->getOneOrNullResult();
	}
}