<?php
namespace Brainstrap\Core\NCBundle\Repository\Cart;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartTypeRepository extends EntityRepository
{
}