security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            nc_interface_index
                # submit the login form here
                check_path: fos_user_security_check

                # the user is redirected here when they need to log in
                login_path: fos_user_security_login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/do, role: ROLE_ADMIN }
        - { path: ^/settings, role: ROLE_ADMIN }