<?php
namespace Brainstrap\Core\NCBundle\Repository\Client;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	public function findClientByCartCode($code)
	{
		$query = $this->createQueryBuilder('client')
			->innerJoin("client.cart", "cart")
			->where('cart.code = :code')
			->setParameter('code', $code)
			->getQuery();

		return $query->getOneOrNullResult();
	}
}