<?php
namespace Brainstrap\Core\NCBundle\Repository\Client;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	/**
	 * Find client by cart code
	 */
	public function findClientByCartCode($code)
	{
		$query = $this->createQueryBuilder('client')
			->innerJoin("client.cart", "cart")
			->where('cart.code = :code')
			->setParameter('code', $code)
			->getQuery();

		return $query->getOneOrNullResult();
	}

	/**
	 * Find client by cart id and client id
	 */
	public function findClientByCartClientId($clientId, $codeId)
	{
		$query = $this->createQueryBuilder('client')
			->innerJoin("client.cart", "cart")
			->where('cart.id = :codeId')
			->andWhere('client.id = :clientId')
			->setParameter('codeId', $codeId)
			->setParameter('clientId', $clientId)
			->getQuery();

		return $query->getOneOrNullResult();
	}
}