<?php
namespace Brainstrap\Core\NCBundle\Repository\Session;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalSessionRepository extends EntityRepository
{
	/**
	 * Find client by cart code
	 */
	public function getActiveSessions()
	{
		$query = $this->createQueryBuilder('psession')
			->getQuery();

		return $query->getArrayResult();
	}

	/**
	 * Find client by cart id and client id
	 */
	public function findClientByCartClientId($clientId, $codeId)
	{
		$query = $this->createQueryBuilder('client')
			->innerJoin("client.cart", "cart")
			->where('cart.id = :codeId')
			->andWhere('client.id = :clientId')
			->setParameter('codeId', $codeId)
			->setParameter('clientId', $clientId)
			->getQuery();

		return $query->getOneOrNullResult();
	}

	/**
	 * 
	 */
	public function getTotalActiveSessions()
	{
		$query = $this->createQueryBuilder('session')
			->select('COUNT(session)')
			->getQuery();

		try {
			$result = $query->getSingleScalarResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			$result = 0;
		}

		return $result;
	}
}