<?php
namespace Brainstrap\Core\NCBundle\Repository\Session;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusSessionRepository extends EntityRepository
{
}