session_personalsession:
    pattern:  /
    defaults: { _controller: "BrainstrapCoreNCBundle:Session/PersonalSession:index" }

session_personalsession_show:
    pattern:  /{id}/show
    defaults: { _controller: "BrainstrapCoreNCBundle:Session/PersonalSession:show" }

session_personalsession_new:
    pattern:  /new
    defaults: { _controller: "BrainstrapCoreNCBundle:Session/PersonalSession:new" }

session_personalsession_create:
    pattern:  /create
    defaults: { _controller: "BrainstrapCoreNCBundle:Session/PersonalSession:create" }
    requirements: { _method: post }

session_personalsession_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BrainstrapCoreNCBundle:Session/PersonalSession:edit" }

session_personalsession_update:
    pattern:  /{id}/update
    defaults: { _controller: "BrainstrapCoreNCBundle:Session/PersonalSession:update" }
    requirements: { _method: post|put }

session_personalsession_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BrainstrapCoreNCBundle:Session/PersonalSession:delete" }
    requirements: { _method: post|delete }
