<?php

namespace Brainstrap\Core\NCBundle\Repository\Reports;

use Doctrine\ORM\EntityRepository;

/**
 * SessionReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionReportRepository extends EntityRepository
{
	/**
	 * Get report by session id
	 */
	public function getReportBySessionId($sessionId)
	{
		$query = $this->createQueryBuilder('sr')
			->where('sr.sessionId = :sessionId')
			->setParameter('sessionId', $sessionId)
			->getQuery();

		return $query->getOneOrNullResult();		
	}
}
